alias claude='node /data/data/com.termux/files/usr/lib/node_modules/@anthropic-ai/claude-code/cli.js'
export TMPDIR=$PREFIX/tmp
export PATH="$HOME/bin:$PATH"
(python ~/stage-server.py &) >/dev/null 2>&1
